name: json_client
author: Demis Bellot <demis.bellot@gmail.com>
version: 0.1.3
homepage: https://github.com/dartist/json_client
description: A generic async HTTP Client optimized for consuming JSON web services
